ekf_filter_node_map:
  ros__parameters:
    frequency: 10.0
    sensor_timeout: 0.1

    two_d_mode: false
    publish_tf: true
    map_frame: map              # для использования в SLAM/AMCL
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    odom0: /stm_odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true, true, true,
                   false, false, false,
                   false, false, false]
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 1

    # GPS odometry (from navsat_transform_node):

    odom1: /odometry/gps
    odom1_config: [true,  true,  true,
                  false, false, true,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    odom1_queue_size: 1
    # odom1_nodelay: true
    odom1_differential: false
    odom1_relative: false

    imu0: /imu
    # imu0_config: [false, false, false,
    #               false,  false,  false,
    #               false, false, false,
    #               true,  true,  true,
    #               false,  false,  false]
                  
    imu0_config: [false, false, false,
                   false, false, true,
                   false, false, true,
                   false, false, false,
                   false, false, false]
  # x     y      z
  # roll  pitch  yaw
  # vx    vy     vz
  # vroll vpitch vyaw
  # ax    ay     az
    
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 1
    imu0_remove_gravitational_acceleration: true
    

    print_diagnostics: false
    debug: true

    # acceleration_limits: [3.0, 3.0, 0.2, 3.0, 3.0, 3.0]
    

    # deceleration_limits: [3.0, 3.0, 3.0, 3.0, 3.0, 3.0]

    # acceleration_gains: [3.0, 3.0, 0.2, 3.0, 3.0, 3.0]


    # deceleration_gains: [3.0, 3.0, 0.2, 3.0, 3.0, 3.0]

    # dynamic_process_noise_covariance: true

    reset_on_time_jump: true

    # process_noise_covariance:
    #   linear_acceleration: 0.05
    #   angular_velocity: 0.05
    #   position: 0.01
    #   orientation: 0.01
    #   velocity: 0.01

    # Initial estimate error covariance (P)
    # initial_estimate_covariance:
    #   pose: [0.1, 0, 0, 0, 0, 0,
    #          0, 0.1, 0, 0, 0, 0,
    #          0, 0, 0.1, 0, 0, 0,
    #          0, 0, 0, 0.1, 0, 0,
    #          0, 0, 0, 0, 0.1, 0,
    #          0, 0, 0, 0, 0, 0.1]
    #   twist: [0.1, 0, 0, 0, 0, 0,
    #           0, 0.1, 0, 0, 0, 0,
    #           0, 0, 0.1, 0, 0, 0,
    #           0, 0, 0, 0.1, 0, 0,
    #           0, 0, 0, 0, 0.1, 0,
    #           0, 0, 0, 0, 0, 0.1]
    # use control: true
    process_noise_covariance: [1.0,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    1.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    1e-3,   0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.3,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.3,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.01,   0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.5,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.5,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.1,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.3,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.3,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.3,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.3,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.3,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.3]

    

    # initial_estimate_covariance: [1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9]

ekf_filter_node_odom:
  ros__parameters:
    frequency: 20.0
    sensor_timeout: 0.1

    two_d_mode: true
    publish_tf: true
    map_frame: map              # для использования в SLAM/AMCL
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /stm_odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true, true, true,
                   false, false, false,
                   false, false, false]
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 1

    imu0: /imu
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  false,  false,  false,
                  false,  false,  false]
  # x     y      z
  # roll  pitch  yaw
  # vx    vy     vz
  # vroll vpitch vyaw
  # ax    ay     az
    
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true
    

    print_diagnostics: false
    debug: false

    acceleration_limits: [3.0, 3.0, 0.2, 3.0, 3.0, 3.0]


    deceleration_limits: [3.0, 3.0, 3.0, 3.0, 3.0, 3.0]

    acceleration_gains: [3.0, 3.0, 0.2, 3.0, 3.0, 3.0]


    deceleration_gains: [3.0, 3.0, 0.2, 3.0, 3.0, 3.0]

    process_noise_covariance: [1e-3, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    1e-3,  0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    1e-3,  0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.3,   0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.3,   0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.01,  0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.5,    0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.5,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.1,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.3,   0.0,    0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.3,   0.0,    0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.3,   0.0,    0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.3,   0.0,    0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.3,   0.0,
                              0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.3]
    
    # dynamic_process_noise_covariance: true

    reset_on_time_jump: true
    use_control: false
    # initial_estimate_covariance: [1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9]

gps_filter_node:
  ros__parameters:
    frequency: 10.0
    delay: 1.0
    child_frame_id: base_link
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_cartesian_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false

rgbd_odometry:
  ros__parameters:
    frame_id: base_link
    odom_frame_id: odom_rgbd
    publish_tf: False
    approx_sync: True
    queue_size: 30
    guess_frame_id: odom  # если используешь начальное предположение
    wait_for_transform: 1.0
    # frame_id: cam_1
    # subscribe_depth: True
    # subscribe_rgb: True
    # approx_sync: False
    # approx_sync_max_interval: 0.01
    # publish_tf: False
    # wait_imu_to_init: False
    # publish_null_when_lost: False
    # qos: 2
    # qos_camera_info: 2
    # # 0=TORO 1=g2o 2=GTSAM and 3=Ceres
    # Optimizer/Strategy: 2
    # Optimizer/GravitySigma: 0.0
    # # 0=Frame-to-Map (F2M) 1=Frame-to-Frame (F2F) 2=Fovis 3=viso2 4=DVO-SLAM 5=ORB_SLAM2 6=OKVIS 7=LOAM 8=MSCKF_VIO 9=VINS-Fusion 10=OpenVINS 11=FLOAM 12=Open3D
    # Odom/Strategy: 0
    # Odom/ResetCountdown: 1
    # Odom/Holonomic: false
    # # 0=No filtering 1=Kalman filtering 2=Particle filtering
    # Odom/FilteringStrategy: 1
    # Odom/ParticleSize: 500
    # Odom/GuessMotion: true
    # Odom/AlignWithGround: false
    # OdomF2M/MaxSize: 5000
    # OdomF2M/ScanMaxSize: 5000
    # GFTT/MinDistance: 7.0
    # GFTT/QualityLevel: 0.001
    # GFTT/BlockSize: 3
    # GFTT/UseHarrisDetector: true
    # GFTT/K: 0.04
    # SURF/Extended: true
    # SURF/HessianThreshold: 500
    # SURF/Octaves: 4
    # SURF/OctaveLayers: 4
    # SURF/Upright: false
    # SURF/GpuVersion: false
    # SURF/GpuKeypointsRatio: 0.01
    # SIFT/NFeatures: 1000
    # SIFT/NOctaveLayers: 4
    # SIFT/RootSIFT: false
    # FREAK/OrientationNormalized: true
    # FREAK/ScaleNormalized: true
    # FREAK/PatternScale: 30
    # FREAK/NOctaves: 4
    # KAZE/Extended: true
    # KAZE/Upright: false
    # KAZE/NOctaves: 4
    # KAZE/NOctaveLayers: 4
    # # 0=DIFF_PM_G1 1=DIFF_PM_G2 2=DIFF_WEICKERT or 3=DIFF_CHARBONNIER
    # KAZE/Diffusivity: 1
    # BRIEF/Bytes: 64
    # # Motion estimation approach: 0:3D->3D 1:3D->2D (PnP) 2:2D->2D (Epipolar Geometry)
    # Vis/EstimationType: 1
    # Vis/ForwardEstOnly: true
    # # 0=SURF 1=SIFT 2=ORB 3=FAST/FREAK 4=FAST/BRIEF 5=GFTT/FREAK 6=GFTT/BRIEF 7=BRISK 8=GFTT/ORB 9=KAZE 10=ORB-OCTREE 11=SuperPoint 12=SURF/FREAK 13=GFTT/DAISY 14=SURF/DAISY 15=PyDetector
    # Vis/FeatureType: 8
    # Vis/DepthAsMask: true
    # Vis/CorGuessWinSize: 40
    # Vis/MaxFeatures: 0
    # Vis/MinDepth: 0.0
    # Vis/MaxDepth: 0.0
    # # 0=Features Matching 1=Optical Flow
    # Vis/CorType: 0
    # # kNNFlannNaive=0 kNNFlannKdTree=1 kNNFlannLSH=2 kNNBruteForce=3 kNNBruteForceGPU=4 BruteForceCrossCheck=5 SuperGlue=6 GMS=7
    # Vis/CorNNType: 1