ekf_filter_node_map:
  ros__parameters:
    frequency: 10.0
    sensor_timeout: 0.1

    two_d_mode: false
    publish_tf: true
    base_link_frame: base_link
    world_frame: map

    odom0: /stm_odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true, true, true,
                   false, false, false,
                   false, false, false]

    odom1: /odometry/gps
    odom1_config: [true,  true,  true,
                  false, false, true,
                  false, false, false,
                  false, false, false,
                  false, false, false]

    imu0: /imu           
    imu0_config: [false, false, false,
                   false, false, true,
                   false, false, true,
                   false, false, false,
                   false, false, false]

ekf_filter_node_odom:
  ros__parameters:
    frequency: 20.0
    sensor_timeout: 0.1

    two_d_mode: true
    publish_tf: true
    base_link_frame: base_link
    world_frame: odom

    odom0: /stm_odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true, true, true,
                   false, false, false,
                   false, false, false]

    imu0: /imu
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  false,  false,  false,
                  false,  false,  false]
  # x     y      z
  # roll  pitch  yaw
  # vx    vy     vz
  # vroll vpitch vyaw
  # ax    ay     az


gps_filter_node:
  ros__parameters:
    frequency: 10.0
    delay: 1.0
    child_frame_id: base_link
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_cartesian_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: true
    wait_for_datum: false