teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 1.5
    scale_linear_turbo:
      x: 2.0
  

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.8

    enable_button: 4
    enable_turbo_button: 5

    require_enable_button: False


    #axes
    # 5 - rt
    # 4 - right y
    # 3 - right x
    # 2 - lt
    # 1 - left y
    # 0 - left x