pointcloud_to_laserscan:
  ros__parameters:
    min_height: -0.10 # Minimum height of the point cloud to include
    max_height: 2.0 # Maximum height of the point cloud to include
    angle_min: -3.14 # Minimum angle (radians)
    angle_max: 3.14 # Maximum angle (radians)
    angle_increment: 0.01 # Angle increment (radians)
    range_min: 1.0 # Minimum range (meters)
    range_max: 25.0 # Maximum range (meters)
    use_inf: True # Use `inf` for no return
    target_frame: lidar_link
    transform_tolerance: 0.05