pointcloud_to_laserscan:
  ros__parameters:
    min_height: -1.1 # Minimum height of the point cloud to include
    max_height: 2.0 # Maximum height of the point cloud to include
    angle_min: -3.14 # Minimum angle (radians)
    angle_max: 3.14 # Maximum angle (radians)
    angle_increment: 0.01 # Angle increment (radians)
    range_min: 1.0 # Minimum range (meters)
    range_max: 20.0 # Maximum range (meters)
    use_inf: True # Use `inf` for no return
    output_frame: base_link # Frame for the LaserScan
    #target_frame: ''
    transform_tolerance: 0.1